/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ApodCard {
        "cardTitle": string;
        "copyright"?: string;
        "date": string;
        "imageUrl": string;
        /**
          * @default false
         */
        "isVideo": boolean;
    }
    interface MarsPhotoCard {
        "cameraName": string;
        "earthDate": string;
        /**
          * @default false
         */
        "favorited": boolean;
        "imgSrc": string;
        "roverName": string;
        "sol": number;
    }
    interface NeoBadge {
        "distanceKm": number;
        /**
          * @default false
         */
        "hazardous": boolean;
        "name": string;
        "velocityKph": number;
    }
}
export interface ApodCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLApodCardElement;
}
export interface MarsPhotoCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMarsPhotoCardElement;
}
declare global {
    interface HTMLApodCardElementEventMap {
        "cardClick": { title: string; date: string };
    }
    interface HTMLApodCardElement extends Components.ApodCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLApodCardElementEventMap>(type: K, listener: (this: HTMLApodCardElement, ev: ApodCardCustomEvent<HTMLApodCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLApodCardElementEventMap>(type: K, listener: (this: HTMLApodCardElement, ev: ApodCardCustomEvent<HTMLApodCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLApodCardElement: {
        prototype: HTMLApodCardElement;
        new (): HTMLApodCardElement;
    };
    interface HTMLMarsPhotoCardElementEventMap {
        "favoriteToggle": { sol: number; favorited: boolean };
    }
    interface HTMLMarsPhotoCardElement extends Components.MarsPhotoCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMarsPhotoCardElementEventMap>(type: K, listener: (this: HTMLMarsPhotoCardElement, ev: MarsPhotoCardCustomEvent<HTMLMarsPhotoCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMarsPhotoCardElementEventMap>(type: K, listener: (this: HTMLMarsPhotoCardElement, ev: MarsPhotoCardCustomEvent<HTMLMarsPhotoCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMarsPhotoCardElement: {
        prototype: HTMLMarsPhotoCardElement;
        new (): HTMLMarsPhotoCardElement;
    };
    interface HTMLNeoBadgeElement extends Components.NeoBadge, HTMLStencilElement {
    }
    var HTMLNeoBadgeElement: {
        prototype: HTMLNeoBadgeElement;
        new (): HTMLNeoBadgeElement;
    };
    interface HTMLElementTagNameMap {
        "apod-card": HTMLApodCardElement;
        "mars-photo-card": HTMLMarsPhotoCardElement;
        "neo-badge": HTMLNeoBadgeElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface ApodCard {
        "cardTitle": string;
        "copyright"?: string;
        "date": string;
        "imageUrl": string;
        /**
          * @default false
         */
        "isVideo"?: boolean;
        "onCardClick"?: (event: ApodCardCustomEvent<{ title: string; date: string }>) => void;
    }
    interface MarsPhotoCard {
        "cameraName": string;
        "earthDate": string;
        /**
          * @default false
         */
        "favorited"?: boolean;
        "imgSrc": string;
        "onFavoriteToggle"?: (event: MarsPhotoCardCustomEvent<{ sol: number; favorited: boolean }>) => void;
        "roverName": string;
        "sol": number;
    }
    interface NeoBadge {
        "distanceKm": number;
        /**
          * @default false
         */
        "hazardous"?: boolean;
        "name": string;
        "velocityKph": number;
    }

    interface ApodCardAttributes {
        "imageUrl": string;
        "cardTitle": string;
        "date": string;
        "copyright": string;
        "isVideo": boolean;
    }
    interface MarsPhotoCardAttributes {
        "imgSrc": string;
        "cameraName": string;
        "earthDate": string;
        "sol": number;
        "roverName": string;
        "favorited": boolean;
    }
    interface NeoBadgeAttributes {
        "name": string;
        "hazardous": boolean;
        "distanceKm": number;
        "velocityKph": number;
    }

    interface IntrinsicElements {
        "apod-card": Omit<ApodCard, keyof ApodCardAttributes> & { [K in keyof ApodCard & keyof ApodCardAttributes]?: ApodCard[K] } & { [K in keyof ApodCard & keyof ApodCardAttributes as `attr:${K}`]?: ApodCardAttributes[K] } & { [K in keyof ApodCard & keyof ApodCardAttributes as `prop:${K}`]?: ApodCard[K] } & OneOf<"imageUrl", ApodCard["imageUrl"], ApodCardAttributes["imageUrl"]> & OneOf<"cardTitle", ApodCard["cardTitle"], ApodCardAttributes["cardTitle"]> & OneOf<"date", ApodCard["date"], ApodCardAttributes["date"]>;
        "mars-photo-card": Omit<MarsPhotoCard, keyof MarsPhotoCardAttributes> & { [K in keyof MarsPhotoCard & keyof MarsPhotoCardAttributes]?: MarsPhotoCard[K] } & { [K in keyof MarsPhotoCard & keyof MarsPhotoCardAttributes as `attr:${K}`]?: MarsPhotoCardAttributes[K] } & { [K in keyof MarsPhotoCard & keyof MarsPhotoCardAttributes as `prop:${K}`]?: MarsPhotoCard[K] } & OneOf<"imgSrc", MarsPhotoCard["imgSrc"], MarsPhotoCardAttributes["imgSrc"]> & OneOf<"cameraName", MarsPhotoCard["cameraName"], MarsPhotoCardAttributes["cameraName"]> & OneOf<"earthDate", MarsPhotoCard["earthDate"], MarsPhotoCardAttributes["earthDate"]> & OneOf<"sol", MarsPhotoCard["sol"], MarsPhotoCardAttributes["sol"]> & OneOf<"roverName", MarsPhotoCard["roverName"], MarsPhotoCardAttributes["roverName"]>;
        "neo-badge": Omit<NeoBadge, keyof NeoBadgeAttributes> & { [K in keyof NeoBadge & keyof NeoBadgeAttributes]?: NeoBadge[K] } & { [K in keyof NeoBadge & keyof NeoBadgeAttributes as `attr:${K}`]?: NeoBadgeAttributes[K] } & { [K in keyof NeoBadge & keyof NeoBadgeAttributes as `prop:${K}`]?: NeoBadge[K] } & OneOf<"name", NeoBadge["name"], NeoBadgeAttributes["name"]> & OneOf<"distanceKm", NeoBadge["distanceKm"], NeoBadgeAttributes["distanceKm"]> & OneOf<"velocityKph", NeoBadge["velocityKph"], NeoBadgeAttributes["velocityKph"]>;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "apod-card": LocalJSX.IntrinsicElements["apod-card"] & JSXBase.HTMLAttributes<HTMLApodCardElement>;
            "mars-photo-card": LocalJSX.IntrinsicElements["mars-photo-card"] & JSXBase.HTMLAttributes<HTMLMarsPhotoCardElement>;
            "neo-badge": LocalJSX.IntrinsicElements["neo-badge"] & JSXBase.HTMLAttributes<HTMLNeoBadgeElement>;
        }
    }
}
